### ISSUE TITLE
HOOKPROTO for vbcc is broken

### ISSUE THREAD

**Issue by sezero** [adtools/SDI#1]
HOOKPROTO for m68k-vbcc is broken because of a typo: vbcc defines `__M68K__` with two leading underscores, whereas SDI_hook.h checks it with only one underscore:
https://github.com/adtools/SDI/blob/master/SDI_hook.h#L124

Changing `_M68K__` to `__M68K__` fixes it and my uHexen2 port outputs audio through AHI with it.

**Comment by jens-maus** [comment]
Then please send over a pull request how this is supposed to be done on github and I will be happy to integrate it.

**Comment by sezero** [comment]
I am having trouble with the github graphical interface. You can pull in this commit:
https://github.com/sezero/SDI/commit/b754eb9164268259468bb2719d52f41f058bcf01
